In [55]:
import pandas as pd

In [57]:
df = pd.read_csv('10K findings.csv')

In [59]:
# First calculate revenue growth if not done
df['Revenue Growth (%)'] = df.groupby('Company')['Total Revenue'].pct_change() * 100

# Now display the selected columns
revenue_growth=df[['Company', 'Year', 'Revenue Growth (%)']]

revenue_growth

     Company  Year  Revenue Growth (%)
0  Microsoft  2024                 NaN
1  Microsoft  2023          -13.547132
2  Microsoft  2022           -6.438902
3      Tesla  2024                 NaN
4      Tesla  2023           -0.938684
5      Tesla  2022          -15.821562
6      Apple  2024                 NaN
7      Apple  2023            6.493506
8      Apple  2022           -8.536585

In [61]:
# First calculate Net Income growth if not done
df['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100

# Now display the selected columns
net_income = df[['Company', 'Year', 'Net Income Growth (%)']]

net_income

     Company  Year  Net Income Growth (%)
0  Microsoft  2024                    NaN
1  Microsoft  2023             -17.898475
2  Microsoft  2022               0.520999
3      Tesla  2024                    NaN
4      Tesla  2023             109.338739
5      Tesla  2022             -15.940964
6      Apple  2024                    NaN
7      Apple  2023               3.476786
8      Apple  2022               2.894995

In [13]:
company_summary = df.groupby('Company')[['Total Revenue', 'Net Income']].sum().sort_values(by='Total Revenue', ascending=False)
company_summary

           Total Revenue  Net Income
Company
Apple        23400000000      290534
Microsoft         655307      233235
Tesla             275925       34714

In [63]:
yearly_summary = df.groupby(['Year', 'Company'])[['Total Revenue', 'Net Income']].sum().reset_index()
yearly_summary

   Year    Company  Total Revenue  Net Income
0  2022      Apple     7500000000       99803
1  2022  Microsoft         198270       72738
2  2022      Tesla          81462       12587
3  2023      Apple     8200000000       96995
4  2023  Microsoft         211915       72361
5  2023      Tesla          96773       14974
6  2024      Apple     7700000000       93736
7  2024  Microsoft         245122       88136
8  2024      Tesla          97690        7153

In [65]:
avg_metrics = df.groupby('Company')[['Total Revenue', 'Net Income', 'Revenue Growth (%)', 'Net Income Growth (%)']].mean()
avg_metrics

,Total Revenue,Net Income,Revenue Growth (%),Net Income Growth (%)
Company,,,,
Apple,7.800000e+09,96844.666667,-1.021539,3.185890
Microsoft,2.184357e+05,77745.000000,-9.993017,-8.688738
Tesla,9.197500e+04,11571.333333,-8.380123,46.698887

In [71]:
max_growth = df.groupby('Company')[['Revenue Growth (%)', 'Net Income Growth (%)']].max()
max_growth

           Revenue Growth (%)  Net Income Growth (%)
Company
Apple                6.493506               3.476786
Microsoft           -6.438902               0.520999
Tesla               -0.938684             109.338739

In [73]:
min_growth = df.groupby('Company')[['Revenue Growth (%)', 'Net Income Growth (%)']].min()
min_growth

           Revenue Growth (%)  Net Income Growth (%)
Company
Apple               -8.536585               2.894995
Microsoft          -13.547132             -17.898475
Tesla              -15.821562             -15.940964

In [12]:
import pandas as pd

# Load the data from the Excel spreadsheet
file_path = '10K findings.csv'
df = pd.read_csv(file_path)

# Calculate year-over-year growth rates for Total Revenue and Net Income
df['Revenue Growth (%)'] = df.groupby('Company')['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby('Company')['Net Income'].pct_change() * 100

# Fill NA values that result from pct_change calculations with 0 or an appropriate value
df.fillna(0, inplace=True)

# Display the dataframe to verify the calculations
print(df)

# Optionally, you could summarize these findings for each company
summary = df.groupby('Company').agg({
    'Revenue Growth (%)': 'mean',
    'Net Income Growth (%)': 'mean'
}).reset_index()

print("\nYear-over-Year Average Growth Rates (%):")
print(summary)

     Company  Year  Total Revenue  Net Income Total Assets   \
0  Microsoft  2024         245122       88136        512163
1  Microsoft  2023         211915       72361        411976
2  Microsoft  2022         198270       72738             0
3      Tesla  2024          97690        7153      122,070
4      Tesla  2023          96773       14974      106,618
5      Tesla  2022          81462       12587             0
6      Apple  2024     7700000000       93736        364980
7      Apple  2023     8200000000       96995        352583
8      Apple  2022     7500000000       99803             0

   Total Liabilities  Cash Flow  Revenue Growth (%)  Net Income Growth (%)
0              243686    118548            0.000000               0.000000
1              205753     87582          -13.547132             -17.898475
2                   0     89035           -6.438902               0.520999
3               48390     14923            0.000000               0.000000
4               43009   13,256            -0.938684             109.338739
5                   0     14724          -15.821562             -15.940964
6              308030  118,254             0.000000               0.000000
7              290437    110543            6.493506               3.476786
8                   0    122151           -8.536585               2.894995

Year-over-Year Average Growth Rates (%):
     Company  Revenue Growth (%)  Net Income Growth (%)
0      Apple           -0.681026               2.123927
1  Microsoft           -6.662011              -5.792492
2      Tesla           -5.586748              31.132592

## Summary of Financial Analysis

### Methodology:
We grouped financial data by Company and Year to observe total revenue and net income trends. Growth rates were calculated using the `pct_change()` function.

Financial Growth Summary (YoY)
Key Highlights by Company:
Apple
Revenue Growth: Slight overall decline of -0.68% YoY.

Net Income Growth: Small positive growth of 2.12%, showing stable profitability.

Insight: Despite a dip in revenue in 2022, Apple maintained profitability with improving net income, indicating efficient cost control and strong margins.

Microsoft
Revenue Growth: Average decline of -6.66% YoY.

Net Income Growth: Decrease of -5.79%, reflecting modestly shrinking profits.

Insight: Microsoft saw a downward trend in both revenue and net income, possibly due to market saturation or increased operational costs.

Tesla
Revenue Growth: Decline of -5.59% YoY, though not drastic.

Net Income Growth: Impressive increase of 31.13%, driven by major improvements from 2023.

Insight: Tesla’s surge in net income despite lower revenue suggests operational efficiency or increased profit margins—potentially from cost-saving innovations or premium pricing.

Overall Observations
Tesla is the most improved in terms of profitability.

Apple remains stable, balancing minor revenue dips with income growth.

Microsoft experienced the steepest decline in both revenue and income, warranting further investigation.

In [24]:
import pandas as pd

# Load the cleaned financial data with year-over-year growth
data = {
    'Company': ['Microsoft', 'Microsoft', 'Microsoft', 'Tesla', 'Tesla', 'Tesla', 'Apple', 'Apple', 'Apple'],
    'Year': [2024, 2023, 2022, 2024, 2023, 2022, 2024, 2023, 2022],
    'Total Revenue': [245122, 211915, 198270, 97690, 96773, 81462, 7700000000, 8200000000, 7500000000],
    'Net Income': [88136, 72361, 72738, 7153, 14974, 12587, 93736, 96995, 99803],
    'Revenue Growth (%)': [0.000, -13.547, -6.439, 0.000, -0.939, -15.822, 0.000, 6.494, -8.537],
    'Net Income Growth (%)': [0.000, -17.898, 0.521, 0.000, 109.339, -15.941, 0.000, 3.477, 2.895]
}

df = pd.DataFrame(data)

# Calculate values to use in chatbot responses
latest_revenue = df[df['Year'] == 2024][['Company', 'Total Revenue']].set_index('Company').to_dict()['Total Revenue']
latest_net_income = df[df['Year'] == 2024][['Company', 'Net Income']].set_index('Company').to_dict()['Net Income']
revenue_growth = df[df['Year'] == 2023][['Company', 'Revenue Growth (%)']].set_index('Company').to_dict()['Revenue Growth (%)']
net_income_growth = df[df['Year'] == 2023][['Company', 'Net Income Growth (%)']].set_index('Company').to_dict()['Net Income Growth (%)']

latest_revenue, latest_net_income, revenue_growth, net_income_growth

({'Microsoft': 245122, 'Tesla': 97690, 'Apple': 7700000000},
 {'Microsoft': 88136, 'Tesla': 7153, 'Apple': 93736},
 {'Microsoft': -13.547, 'Tesla': -0.939, 'Apple': 6.494},
 {'Microsoft': -17.898, 'Tesla': 109.339, 'Apple': 3.477})

In [26]:
def simple_chatbot(company, user_query):
    company = company.title()
    
    if company not in latest_revenue:
        return "Sorry, I don't have data for that company."

    if user_query == "What is the total revenue?":
        return f"{company}'s total revenue in 2024 was ${latest_revenue[company]:,}."
    elif user_query == "What is the net income?":
        return f"{company}'s net income in 2024 was ${latest_net_income[company]:,}."
    elif user_query == "How has revenue changed over the last year?":
        return f"{company}'s revenue changed by {revenue_growth[company]:.2f}% from 2022 to 2023."
    elif user_query == "How has net income changed over the last year?":
        return f"{company}'s net income changed by {net_income_growth[company]:.2f}% from 2022 to 2023."
    else:
        return "Sorry, I can only provide information on predefined queries."

In [32]:
def ask_bot():
    company = input("Enter company: ")
    question = input("Your question: ")
    print(simple_chatbot(company, question))
ask_bot()

Enter company:  Tesla
Your question:  What is the net income?

Tesla's net income in 2024 was $7,153.